<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Booking_model extends CI_Model
{

    public $table = 'booking';
    public $id = 'id';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    function get_booking($tgl_booking,$jam_booking) {

        $this->db->where('tgl_booking',$tgl_booking);
        $this->db->where('jam_booking',$jam_booking);

        $q_date = $this->db->query('SELECT tgl_booking FROM booking WHERE tgl_booking="'.$tgl_booking.'"');

        if ($q_date->num_rows()>28) 
        {
            foreach ($q_date->result() as $row) 
            {
                $this->session->set_flashdata('info', '<span class="text-danger">Booking Untuk Tanggal Yang Anda Pilih Penuh, Silahkan Pilih Tanggal Lain.</span>');
                redirect('booking/create');
            }
        }
        else {
            $q_time = $this->db->query('SELECT tgl_booking, jam_booking FROM booking WHERE tgl_booking="'.$tgl_booking.'" AND jam_booking="'.$jam_booking.'"');
            if ($q_time->num_rows()>4) 
            {
                foreach ($q_time->result() as $row) {
                    $this->session->set_flashdata('jam', '<span class="text-danger">Booking Untuk Jam Yang Anda Pilih Penuh, Silahkan Pilih Jam Lain.</span>');
                redirect('booking/create');
                }
            }
        }
        // return $this->db->get('time')-result();
        // return [];

        // $query8 = $this->db->query("Select * from booking where jam_booking = 8");
        // $query9 = $this->db->query("select * from time where jam_booking = 9");
        // if ($query8 > 10) {
        //     return $this->db->query("select * from time where time_booking not in 8");
        // } else if ($query9 > 1) {
        //     return $this->db->query("select * from time where time_booking not in 9");
        // } else if ($query8 > 1 && $query9 > 1){

        // }


    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
	$this->db->or_like('nama_konsumen', $q);
	$this->db->or_like('plat_nomor', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('nama_mtr', $q);
	$this->db->or_like('jenis_service', $q);
	$this->db->or_like('tgl_booking', $q);
	$this->db->or_like('jam_booking', $q);
	$this->db->or_like('activated', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
	$this->db->or_like('nama_konsumen', $q);
	$this->db->or_like('plat_nomor', $q);
	$this->db->or_like('no_telp', $q);
	$this->db->or_like('nama_mtr', $q);
	$this->db->or_like('jenis_service', $q);
	$this->db->or_like('tgl_booking', $q);
	$this->db->or_like('jam_booking', $q);
	$this->db->or_like('activated', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function appapprove($id) 
    {
       $this->db->from('booking');
       $this->db->where('id', $id);
       $this->db->set('activated', 'activated');
       $this->db->update('booking');
    }

    public function btlapprove($id) 
    {
       $this->db->from('booking');
       $this->db->where('id', $id);
       $this->db->set('activated', '');
       $this->db->update('booking');
    }

    function get_dropdown() {
        $this->db->from('motorcycle');
        $query = $this->db->get();
        return $query->result();
    }
}

/* End of file Booking_model.php */
/* Location: ./application/models/Booking_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-09-17 18:17:27 */
/* http://harviacode.com */